// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oblig2VerkhalantsevaAPI.Data;

#nullable disable

namespace Oblig2VerkhalantsevaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241028220816_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.32");

            modelBuilder.Entity("Oblig2VerkhalantsevaAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Author", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "F. Scott",
                            LastName = "Fitzgerald"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Harper",
                            LastName = "Lee"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "George",
                            LastName = "Orwell"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Knut",
                            LastName = "Hamsun"
                        });
                });

            modelBuilder.Entity("Oblig2VerkhalantsevaAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Book", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            Description = "A classic novel by F. Scott Fitzgerald",
                            LanguageId = 1,
                            PublisherId = 1,
                            Title = "The Great Gatsby",
                            Year = 1925
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 2,
                            Description = "A novel by Harper Lee about racial injustice",
                            LanguageId = 1,
                            PublisherId = 2,
                            Title = "To Kill a Mockingbird",
                            Year = 1960
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 3,
                            Description = "A dystopian novel by George Orwell",
                            LanguageId = 1,
                            PublisherId = 3,
                            Title = "1984",
                            Year = 1949
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CategoryId = 4,
                            Description = "A psychological novel by Knut Hamsun",
                            LanguageId = 2,
                            PublisherId = 4,
                            Title = "Hunger",
                            Year = 1890
                        });
                });

            modelBuilder.Entity("Oblig2VerkhalantsevaAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Classic Literature"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Historical Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dystopian"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Psychological Fiction"
                        });
                });

            modelBuilder.Entity("Oblig2VerkhalantsevaAPI.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Language", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Norwegian"
                        });
                });

            modelBuilder.Entity("Oblig2VerkhalantsevaAPI.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Publisher", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Scribner"
                        },
                        new
                        {
                            Id = 2,
                            Name = "J.B. Lippincott & Co."
                        },
                        new
                        {
                            Id = 3,
                            Name = "Secker & Warburg"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gyldendal Norsk Forlag"
                        });
                });

            modelBuilder.Entity("Oblig2VerkhalantsevaAPI.Models.Book", b =>
                {
                    b.HasOne("Oblig2VerkhalantsevaAPI.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oblig2VerkhalantsevaAPI.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oblig2VerkhalantsevaAPI.Models.Language", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oblig2VerkhalantsevaAPI.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");

                    b.Navigation("Language");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Oblig2VerkhalantsevaAPI.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Oblig2VerkhalantsevaAPI.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Oblig2VerkhalantsevaAPI.Models.Language", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Oblig2VerkhalantsevaAPI.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
